# Generated by Django 2.0.4 on 2018-04-17 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('email', models.EmailField(max_length=255, verbose_name='email')),
                ('telefone', models.IntegerField(verbose_name='telefone')),
                ('cpf', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d+$')], verbose_name='cpf')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('R', 'Rua'), ('A', 'Av'), ('K', 'Km'), ('L', 'Lot')], max_length=1, verbose_name='tipo')),
                ('cep', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d+$')], verbose_name='cep')),
                ('rua', models.CharField(max_length=255, verbose_name='Rua')),
                ('numero', models.IntegerField(verbose_name='numero')),
                ('complemento', models.CharField(max_length=100, verbose_name='complemento')),
            ],
        ),
    ]
