# Generated by Django 2.0.4 on 2018-04-17 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='numero')),
                ('data', models.DateField(auto_now_add=True, verbose_name='data')),
                ('loja', models.CharField(max_length=255, verbose_name='loja')),
                ('Valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
            ],
        ),
    ]
