# Generated by Django 2.0.4 on 2018-04-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180418_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='numero'),
        ),
    ]
