# Generated by Django 2.0.4 on 2018-04-17 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_auto_20180417_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(verbose_name='codigo')),
                ('descricao', models.CharField(max_length=255, verbose_name='descricao')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unitário')),
                ('quantidade', models.IntegerField(verbose_name='quantidade')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='numero')),
                ('data', models.DateField(auto_now_add=True, verbose_name='data')),
                ('loja', models.CharField(max_length=255, verbose_name='loja')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['numero'],
            },
        ),
    ]
