# Generated by Django 2.0.4 on 2018-04-17 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180417_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Pedido'),
            preserve_default=False,
        ),
    ]
